spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Hikari
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.connection-test-query=SELECT 1

# Redis
spring.data.redis.url=${REDIS_URL:redis://localhost:6379}
spring.data.redis.host=red-d7p4of1f9bms7399bao0
spring.data.redis.port=6379
spring.data.redis.timeout=2000

# AWS
aws.s3.bucket-name=surf-champ-videos
aws.region=us-east-1
aws.access.key.id=${AWS_ACCESS_KEY:}
aws.secret.access.key=${AWS_SECRET_KEY:}


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=mySecretKey123456789012345678901234567890
jwt.expiration-ms=86400000

# Server
server.port=${PORT:8080}

# Upload
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# CORS
cors.allowed-origins=http://localhost:3000,http://localhost:4200

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d7p5me3eo5us73dn2vm0-a:5432/surf_champ?sslmode=require
spring.datasource.username=surf_champ_user
spring.datasource.password=ioda0X1ffeocquT5Z0CsBNNyJk8vLZ00
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Desativa só S3 auto (se precisar)
spring.autoconfigure.exclude=io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration

hazelcast.network.rest-api.enabled=true